version: "3.8"
services:
  ml-elec-api:
    image: jaimecespedessisniega/ml-elec-api
    restart: on-failure
    ports:
      - "5000:5000"
    networks:
      - ml-elec
    env_file:
      - env-api.env
    environment:
      NUM_WORKERS: 1
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://drift-detection:5001/health" ]
        interval: 30s
        timeout: 10s
        retries: 5
    depends_on:
      - drift-detection

  drift-detection:
    image: jaimecespedessisniega/drift-detection
    expose:
      - "5001"
    networks:
      - ml-elec

  prometheus:
    image: prom/prometheus:v2.32.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus
    networks:
      - ml-elec
    depends_on:
      - ml-elec-api

  graphana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - ml-elec
    env_file:
      - env-grafana.env
    depends_on:
      - prometheus

networks:
  ml-elec:
    driver: bridge
