version: "3.8"
services:
  ml-elec-api:
    image: jaimecespedessisniega/ml-elec-api
    ports:
      - "5000:5000"
    networks:
      - ml-elec
    env_file:
      - env-model.env
      - env-mongodb.env
    environment:
      - NUM_WORKERS=5

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus
    networks:
      - ml-elec
    depends_on:
      - ml-elec-api

  graphana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ml-elec
    depends_on:
      - prometheus

networks:
  ml-elec:
    driver: bridge
