global: 
  scrape_interval: 15s
 
scrape_configs: 
  - job_name: prometheus 
    static_configs: 
      - targets: ["localhost:9090"]
 
  - job_name: ml-elec-api
    metrics_path: /api/v1/metrics
    dns_sd_configs:
      - names: ["ml-elec-api"]
        port: 5000
        type: A
        refresh_interval: 5s

  - job_name: drift-detection
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["drift-detection"]
        port: 5001
        type: A
        refresh_interval: 5s