{
 "title": "ML Model Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Model Predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Class labels ratio - Current",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_prediction_total / scalar(sum(model_prediction_total))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Class labels ratio - Historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "rate(model_prediction_total[5m]) / scalar(sum(rate(model_prediction_total[5m])))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  { "title": "Model Features", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "nswdemand - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nswdemand_distribution_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nswdemand_distribution_bucket[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nswdemand_distribution_bucket[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(nswdemand_distribution_bucket[5m])) by (le))",
     "legendFormat": "25th"
    }
   ]
  },
  {
   "title": "vicprice - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vicprice_distribution_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vicprice_distribution_bucket[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vicprice_distribution_bucket[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(vicprice_distribution_bucket[5m])) by (le))",
     "legendFormat": "25th"
    }
   ]
  },
  { "title": "Drift Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Covariate Drift - Threshold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "test_stat", "legendFormat": "Test Statistic" },
    { "expr": "threshold", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Covariate Drift - Flag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "drift_flag" }
   ]
  }
 ]
}